import { ClaimReportRecord } from "../reports/types";

export const sampleClaimReportRecords: ClaimReportRecord[] = [
  {
    claim: {
      id: "claim-demo-1",
      claimText: "Archive memorandum indicates Operation Lantern logistics were coordinated through Office Meridian in 1962.",
      canonicalFingerprint: "operation_lantern|coordinated_by|office_meridian|1962",
      subject: "Operation Lantern",
      predicate: "coordinated_by",
      object: "Office Meridian",
      timeStart: "1962-01-01",
      timeEnd: "1962-12-31",
      location: "Washington, D.C.",
      modality: "asserted_fact",
      polarity: "affirmed",
      publicImpact: true,
    },
    assessment: {
      claimId: "claim-demo-1",
      modelVersion: "truth-engine-v2.0-demo",
      posteriorTruthScore: 0.83,
      truthState: "supported",
      releaseState: "auto_release",
      confidenceBand: 0.83,
      features: {
        evidenceSupport: 0.82,
        sourceReliability: 0.8,
        provenanceIntegrity: 0.87,
        independenceAdjustedCorroboration: 0.72,
        temporalCoherence: 0.9,
        causalCoherence: 0.78,
        contradictionPressure: 0.18,
        deceptionSignal: 0.11,
        revisionStability: 0.79,
      },
      explanation: {
        independentSupportingSourceCount: 2,
        independentContradictingSourceCount: 0,
        dependencyCollapseFactor: 0.12,
        reviewReasons: [],
        releaseRationale: [
          "Primary archive note and hearing excerpt converge on the same logistics office.",
          "Minor contradiction exists in later press framing but does not outweigh direct records.",
        ],
      },
    },
    evidence: [
      {
        span: {
          id: "ev-demo-1",
          claimId: "claim-demo-1",
          sourceVersionId: "sv-demo-1",
          quotedText: "Office Meridian coordinated Lantern logistics during the second quarter of 1962.",
          evidenceRole: "supporting",
          pageNumber: 4,
          sectionLabel: "Logistics Summary",
          charStart: 120,
          charEnd: 201,
          lineStart: 12,
          lineEnd: 15,
          extractionConfidence: 0.96,
        },
        sourceVersion: {
          id: "sv-demo-1",
          sourceId: "src-demo-1",
          versionNumber: 1,
          contentHash: "hash-demo-1",
          extractionMethod: "manual_archive_parse",
          extractionConfidence: 0.95,
        },
        source: {
          id: "src-demo-1",
          title: "Lantern Logistics Memorandum",
          sourceType: "archive_scan",
          origin: "National Records Collection",
          author: "Records Division",
          publisher: "National Records Collection",
          publishedAt: "1962-08-01",
          reliabilityPrior: 0.87,
          chainOfCustodyScore: 0.91,
          primarySource: true,
        },
      },
      {
        span: {
          id: "ev-demo-2",
          claimId: "claim-demo-1",
          sourceVersionId: "sv-demo-2",
          quotedText: "The Meridian office handled the routing and supply channel.",
          evidenceRole: "supporting",
          pageNumber: 18,
          sectionLabel: "Hearing Transcript",
          charStart: 30,
          charEnd: 92,
          lineStart: 8,
          lineEnd: 10,
          extractionConfidence: 0.84,
        },
        sourceVersion: {
          id: "sv-demo-2",
          sourceId: "src-demo-2",
          versionNumber: 1,
          contentHash: "hash-demo-2",
          extractionMethod: "ocr_v2",
          extractionConfidence: 0.83,
        },
        source: {
          id: "src-demo-2",
          title: "Committee Hearing Excerpt",
          sourceType: "transcript",
          origin: "Congressional Archive",
          author: "Committee Clerk",
          publisher: "Congressional Archive",
          publishedAt: "1963-02-12",
          reliabilityPrior: 0.78,
          chainOfCustodyScore: 0.8,
          primarySource: true,
        },
      },
    ],
  },
  {
    claim: {
      id: "claim-demo-2",
      claimText: "Later media summaries stated that no dedicated coordination office existed for Operation Lantern.",
      canonicalFingerprint: "operation_lantern|no_coordination_office",
      subject: "Operation Lantern",
      predicate: "coordination_office",
      object: "none",
      timeStart: "1975-01-01",
      timeEnd: "1975-12-31",
      location: "United States",
      modality: "asserted_fact",
      polarity: "affirmed",
      publicImpact: true,
    },
    assessment: {
      claimId: "claim-demo-2",
      modelVersion: "truth-engine-v2.0-demo",
      posteriorTruthScore: 0.39,
      truthState: "contested",
      releaseState: "review_required",
      confidenceBand: 0.39,
      features: {
        evidenceSupport: 0.42,
        sourceReliability: 0.48,
        provenanceIntegrity: 0.45,
        independenceAdjustedCorroboration: 0.33,
        temporalCoherence: 0.65,
        causalCoherence: 0.44,
        contradictionPressure: 0.71,
        deceptionSignal: 0.51,
        revisionStability: 0.31,
      },
      explanation: {
        independentSupportingSourceCount: 1,
        independentContradictingSourceCount: 1,
        dependencyCollapseFactor: 0.42,
        reviewReasons: ["high_contradiction", "weak_provenance"],
        releaseRationale: [
          "The claim is undercut by earlier primary records that identify an office by name.",
          "Later summaries appear derivative and exhibit weak provenance integrity.",
          "High contradiction and weak provenance require reviewer validation.",
        ],
      },
    },
    evidence: [
      {
        span: {
          id: "ev-demo-3",
          claimId: "claim-demo-2",
          sourceVersionId: "sv-demo-3",
          quotedText: "No separate logistics office was ever constituted for Lantern.",
          evidenceRole: "supporting",
          pageNumber: 2,
          sectionLabel: "Magazine Summary",
          charStart: 14,
          charEnd: 79,
          lineStart: 3,
          lineEnd: 5,
          extractionConfidence: 0.8,
        },
        sourceVersion: {
          id: "sv-demo-3",
          sourceId: "src-demo-3",
          versionNumber: 1,
          contentHash: "hash-demo-3",
          extractionMethod: "manual_entry",
          extractionConfidence: 0.82,
        },
        source: {
          id: "src-demo-3",
          title: "Lantern Retrospective Summary",
          sourceType: "article",
          origin: "Weekly Review",
          author: "Editorial Desk",
          publisher: "Weekly Review",
          publishedAt: "1975-06-19",
          reliabilityPrior: 0.41,
          chainOfCustodyScore: 0.4,
          primarySource: false,
        },
      },
      {
        span: {
          id: "ev-demo-4",
          claimId: "claim-demo-2",
          sourceVersionId: "sv-demo-1",
          quotedText: "Office Meridian coordinated Lantern logistics during the second quarter of 1962.",
          evidenceRole: "contradicting",
          pageNumber: 4,
          sectionLabel: "Logistics Summary",
          charStart: 120,
          charEnd: 201,
          lineStart: 12,
          lineEnd: 15,
          extractionConfidence: 0.96,
        },
        sourceVersion: {
          id: "sv-demo-1",
          sourceId: "src-demo-1",
          versionNumber: 1,
          contentHash: "hash-demo-1",
          extractionMethod: "manual_archive_parse",
          extractionConfidence: 0.95,
        },
        source: {
          id: "src-demo-1",
          title: "Lantern Logistics Memorandum",
          sourceType: "archive_scan",
          origin: "National Records Collection",
          author: "Records Division",
          publisher: "National Records Collection",
          publishedAt: "1962-08-01",
          reliabilityPrior: 0.87,
          chainOfCustodyScore: 0.91,
          primarySource: true,
        },
      },
    ],
    reviewTasks: [
      {
        id: "review-demo-1",
        type: "contradiction_resolution",
        priority: "high",
        status: "open",
        subjectId: "claim-demo-2",
        title: "Resolve Operation Lantern office contradiction",
        summary: "Validate whether the magazine summary is derivative of a later public relations memo.",
        payload: {
          reasonCode: "primary_secondary_conflict",
        },
        createdAt: "2026-04-17T12:00:00.000Z",
        updatedAt: "2026-04-17T12:00:00.000Z",
      },
    ],
  },
];
