#!/usr/bin/env python3
import json
import sys
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

def build_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="DossierTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=28,
        textColor=colors.HexColor("#13233A"),
        spaceAfter=12,
        alignment=TA_LEFT,
    ))
    styles.add(ParagraphStyle(
        name="SectionHeader",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=17,
        textColor=colors.HexColor("#17365D"),
        spaceBefore=8,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        name="BodySmall",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="Meta",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#3A4A5C"),
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        name="MonoNote",
        parent=styles["BodyText"],
        fontName="Courier",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#27384C"),
        spaceAfter=3,
    ))
    return styles

def metadata_table(metadata, styles):
    rows = [
        ["Report ID", metadata.get("reportId", "")],
        ["Product", metadata.get("product", "")],
        ["Generated", metadata.get("createdAt", "")],
        ["Generated By", metadata.get("generatedBy", "")],
        ["Classification", metadata.get("classification", "")],
        ["Subject", metadata.get("subject", "")],
    ]
    table = Table(rows, colWidths=[1.35*inch, 4.85*inch], hAlign="LEFT")
    table.setStyle(TableStyle([
        ("FONTNAME", (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("LEADING", (0,0), (-1,-1), 12),
        ("TEXTCOLOR", (0,0), (-1,-1), colors.HexColor("#10243E")),
        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#EAF1F8")),
        ("BOX", (0,0), (-1,-1), 0.5, colors.HexColor("#A9B8C8")),
        ("INNERGRID", (0,0), (-1,-1), 0.35, colors.HexColor("#C7D2DE")),
        ("LEFTPADDING", (0,0), (-1,-1), 6),
        ("RIGHTPADDING", (0,0), (-1,-1), 6),
        ("TOPPADDING", (0,0), (-1,-1), 6),
        ("BOTTOMPADDING", (0,0), (-1,-1), 6),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
    ]))
    return table

def summary_table(records):
    rows = [["Claim", "Truth State", "Score", "Release", "Evidence"]]
    for record in records:
        rows.append([
            record["claim"]["claimText"][:78],
            record["assessment"]["truthState"],
            f'{record["assessment"]["posteriorTruthScore"]:.3f}',
            record["assessment"]["releaseState"],
            str(len(record.get("evidence", []))),
        ])
    table = Table(rows, colWidths=[3.25*inch, 1.0*inch, 0.6*inch, 1.0*inch, 0.55*inch], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#17365D")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 8.5),
        ("LEADING", (0,0), (-1,-1), 11),
        ("GRID", (0,0), (-1,-1), 0.35, colors.HexColor("#BAC7D4")),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#F5F8FB")]),
        ("LEFTPADDING", (0,0), (-1,-1), 5),
        ("RIGHTPADDING", (0,0), (-1,-1), 5),
        ("TOPPADDING", (0,0), (-1,-1), 5),
        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
    ]))
    return table

def bullet_lines(lines, styles):
    story = []
    for line in lines:
        story.append(Paragraph(f"&bull; {line}", styles["BodySmall"]))
    return story

def build_story(dossier):
    styles = build_styles()
    story = []

    story.append(Paragraph(dossier["metadata"]["title"], styles["DossierTitle"]))
    story.append(Paragraph("Veritas Systems - Provenance Chain Evidence Dossier", styles["Meta"]))
    story.append(Spacer(1, 0.12 * inch))
    story.append(metadata_table(dossier["metadata"], styles))
    story.append(Spacer(1, 0.18 * inch))

    story.append(Paragraph("Executive Summary", styles["SectionHeader"]))
    story.extend(bullet_lines(dossier.get("executiveSummary", []), styles))
    story.append(Spacer(1, 0.12 * inch))

    story.append(Paragraph("Release Recommendation", styles["SectionHeader"]))
    story.append(Paragraph(dossier.get("releaseRecommendation", ""), styles["BodySmall"]))
    story.append(Spacer(1, 0.12 * inch))

    story.append(Paragraph("Chain of Custody Notes", styles["SectionHeader"]))
    story.extend(bullet_lines(dossier.get("chainOfCustodyNotes", []), styles))
    story.append(Spacer(1, 0.16 * inch))

    story.append(Paragraph("Claim Assessment Summary", styles["SectionHeader"]))
    story.append(summary_table(dossier.get("records", [])))
    story.append(PageBreak())

    for index, record in enumerate(dossier.get("records", []), start=1):
        story.append(Paragraph(f"Claim {index}", styles["SectionHeader"]))
        story.append(Paragraph(record["claim"]["claimText"], styles["BodySmall"]))
        story.append(Paragraph(
            f'Truth state: <b>{record["assessment"]["truthState"]}</b> | '
            f'Posterior truth score: <b>{record["assessment"]["posteriorTruthScore"]:.3f}</b> | '
            f'Release state: <b>{record["assessment"]["releaseState"]}</b>',
            styles["BodySmall"],
        ))

        story.append(Spacer(1, 0.08 * inch))
        story.append(Paragraph("Assessment Notes", styles["SectionHeader"]))
        story.extend(bullet_lines(record["assessment"].get("explanation", []), styles))

        evidence_rows = [["Role", "Source", "Excerpt"]]
        for ev in record.get("evidence", []):
            evidence_rows.append([
                ev["span"]["evidenceRole"],
                ev["source"]["title"],
                ev["span"]["quotedText"][:130],
            ])
        ev_table = Table(evidence_rows, colWidths=[0.9*inch, 1.9*inch, 4.0*inch], repeatRows=1)
        ev_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#DDE8F4")),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,-1), 8.5),
            ("LEADING", (0,0), (-1,-1), 11),
            ("GRID", (0,0), (-1,-1), 0.35, colors.HexColor("#C3CFDA")),
            ("LEFTPADDING", (0,0), (-1,-1), 5),
            ("RIGHTPADDING", (0,0), (-1,-1), 5),
            ("TOPPADDING", (0,0), (-1,-1), 5),
            ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ]))
        story.append(Spacer(1, 0.08 * inch))
        story.append(Paragraph("Evidence Packet", styles["SectionHeader"]))
        story.append(ev_table)

        prov = next((item for item in dossier.get("provenance", {}).get("dossiers", []) if item["claimId"] == record["claim"]["id"]), None)
        if prov:
            story.append(Spacer(1, 0.12 * inch))
            story.append(Paragraph("Provenance Path", styles["SectionHeader"]))
            for step in prov.get("pathSteps", []):
                story.append(Paragraph(
                    f'{step["step"]}. {step["fromLabel"]} -> {step["relation"]} -> {step["toLabel"]}',
                    styles["BodySmall"],
                ))
                if step.get("note"):
                    story.append(Paragraph(f'    note: {step["note"]}', styles["MonoNote"]))

        if index < len(dossier.get("records", [])):
            story.append(PageBreak())

    story.append(PageBreak())
    story.append(Paragraph("Conclusion", styles["SectionHeader"]))
    story.extend(bullet_lines(dossier.get("conclusion", []), styles))
    return story

def main():
    if len(sys.argv) != 3:
        raise SystemExit("Usage: render_dossier_pdf.py <input_json> <output_pdf>")

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    dossier = json.loads(input_path.read_text(encoding="utf-8"))
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=0.72 * inch,
        rightMargin=0.72 * inch,
        topMargin=0.72 * inch,
        bottomMargin=0.68 * inch,
        title=dossier.get("metadata", {}).get("title", "Evidence Dossier"),
        author="Veritas Systems",
    )
    story = build_story(dossier)
    doc.build(story)

if __name__ == "__main__":
    main()
