import { evaluateClaimV2 } from "../core/truth-engine-v2.js";
import { EvaluateClaimInput } from "../core/types.js";

const payload: EvaluateClaimInput = {
  claim: {
    id: "clm_blackout_001",
    claimText: "The regional blackout on June 3, 1977 was preceded by a documented transformer fire at Plant A.",
    subject: "regional blackout on June 3, 1977",
    predicate: "was preceded by",
    object: "documented transformer fire at Plant A",
    polarity: "affirmed",
    modality: "asserted_fact",
    canonicalFingerprint: "blackout_1977|preceded_by|transformer_fire_plant_a",
    timeStart: "1977-06-03T00:00:00Z",
    timeEnd: "1977-06-03T23:59:59Z",
    location: "Plant A",
    publicImpact: true,
  },
  evidence: [
    {
      span: {
        id: "ev_1",
        claimId: "clm_blackout_001",
        sourceVersionId: "sv_1",
        quotedText: "At 18:42, operators recorded a transformer fire at Plant A shortly before the regional blackout sequence began.",
        evidenceRole: "supporting",
        pageNumber: 12,
        lineStart: 3,
        lineEnd: 7,
        extractionConfidence: 0.96,
      },
      sourceVersion: {
        id: "sv_1",
        sourceId: "src_1",
        versionNumber: 1,
        extractionMethod: "ocr_v3",
        extractionConfidence: 0.94,
        contentHash: "hash-src1-v1",
      },
      source: {
        id: "src_1",
        title: "Utility Incident Log",
        sourceType: "government_record",
        origin: "State Utilities Archive",
        author: "Operations Division",
        publisher: "State Utilities Archive",
        publishedAt: "1977-06-10T00:00:00Z",
        acquiredAt: "2026-04-17T00:00:00Z",
        reliabilityPrior: 0.90,
        chainOfCustodyScore: 0.93,
        primarySource: true,
      },
    },
    {
      span: {
        id: "ev_2",
        claimId: "clm_blackout_001",
        sourceVersionId: "sv_2",
        quotedText: "Maintenance crews saw flame and smoke at Plant A before the wider grid failure.",
        evidenceRole: "supporting",
        pageNumber: 4,
        extractionConfidence: 0.87,
      },
      sourceVersion: {
        id: "sv_2",
        sourceId: "src_2",
        versionNumber: 1,
        extractionMethod: "transcript_parser",
        extractionConfidence: 0.88,
        contentHash: "hash-src2-v1",
      },
      source: {
        id: "src_2",
        title: "Witness Interview Transcript",
        sourceType: "transcript",
        origin: "Public Inquiry Archive",
        author: "Witness C",
        publisher: "Public Inquiry",
        publishedAt: "1977-07-02T00:00:00Z",
        acquiredAt: "2026-04-17T00:00:00Z",
        reliabilityPrior: 0.72,
        chainOfCustodyScore: 0.78,
        primarySource: true,
      },
    },
    {
      span: {
        id: "ev_3",
        claimId: "clm_blackout_001",
        sourceVersionId: "sv_3",
        quotedText: "Officials stated there was no confirmed fire at Plant A before the outage.",
        evidenceRole: "contradicting",
        pageNumber: 1,
        extractionConfidence: 0.85,
      },
      sourceVersion: {
        id: "sv_3",
        sourceId: "src_3",
        versionNumber: 2,
        extractionMethod: "manual_entry",
        extractionConfidence: 0.90,
        contentHash: "hash-src3-v2",
        supersedesVersionId: "sv_3_old",
        revisionReason: "clarification",
      },
      source: {
        id: "src_3",
        title: "Agency Press Statement",
        sourceType: "press_release",
        origin: "Regional Energy Agency",
        author: "Press Office",
        publisher: "Regional Energy Agency",
        publishedAt: "1977-06-05T00:00:00Z",
        acquiredAt: "2026-04-17T00:00:00Z",
        reliabilityPrior: 0.58,
        chainOfCustodyScore: 0.80,
        primarySource: false,
      },
    },
  ],
  claimRelations: [
    {
      fromClaimId: "clm_blackout_001",
      toClaimId: "clm_blackout_001_counter",
      relationType: "contradicts",
      confidence: 0.72,
    },
    {
      fromClaimId: "clm_blackout_001",
      toClaimId: "clm_blackout_001_reframe",
      relationType: "reframes",
      confidence: 0.40,
    },
  ],
  sourceLineage: [
    {
      childSourceId: "src_3",
      parentSourceId: "src_1",
      lineageType: "summary_of",
      confidence: 0.22,
    },
  ],
  causalLinks: [
    {
      causeClaimId: "clm_blackout_001",
      effectClaimId: "clm_grid_failure_001",
      confidence: 0.76,
      relationLabel: "precursor_event",
    },
  ],
};

const result = evaluateClaimV2(payload);
console.log(JSON.stringify(result, null, 2));
