import { ReportDocument } from "./types.js";

function esc(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

export function exportReportAsHtml(report: ReportDocument): string {
  const records = report.records.map((record, idx) => `
    <section class="record">
      <h3>${idx + 1}. ${esc(record.claim.claimText)}</h3>
      <p><strong>Truth state:</strong> ${esc(record.assessment.truthState)}</p>
      <p><strong>Posterior truth score:</strong> ${record.assessment.posteriorTruthScore.toFixed(3)}</p>
      <p><strong>Release state:</strong> ${esc(record.assessment.releaseState)}</p>
      <p><strong>Evidence count:</strong> ${record.evidence.length}</p>
      ${record.fusedSummary ? `<p><strong>Multimodal support:</strong> ${record.fusedSummary.structuralSupportScore.toFixed(3)} (${record.fusedSummary.modalityCoverage.join(", ")})</p>` : ""}
      <ul>
        ${record.evidence.slice(0, 5).map((bundle) => `<li>${esc(bundle.source.title)} — “${esc(bundle.span.quotedText)}”</li>`).join("")}
      </ul>
    </section>
  `).join("");

  return `
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${esc(report.metadata.title)}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #111; }
    h1, h2, h3 { margin-bottom: 0.4rem; }
    .meta, .record { margin-bottom: 1.5rem; }
    .record { border-top: 1px solid #ddd; padding-top: 1rem; }
    ul { margin-top: 0.5rem; }
  </style>
</head>
<body>
  <h1>${esc(report.metadata.title)}</h1>
  <div class="meta">
    <p><strong>Report ID:</strong> ${esc(report.metadata.reportId)}</p>
    <p><strong>Product:</strong> ${esc(report.metadata.product)}</p>
    <p><strong>Generated by:</strong> ${esc(report.metadata.generatedBy)}</p>
    <p><strong>Created at:</strong> ${esc(report.metadata.createdAt)}</p>
    ${report.metadata.classification ? `<p><strong>Classification:</strong> ${esc(report.metadata.classification)}</p>` : ""}
    ${report.metadata.subject ? `<p><strong>Subject:</strong> ${esc(report.metadata.subject)}</p>` : ""}
  </div>
  <h2>Executive Summary</h2>
  <ul>${report.executiveSummary.map((line) => `<li>${esc(line)}</li>`).join("")}</ul>
  <h2>Claim Records</h2>
  ${records}
  <h2>Conclusion</h2>
  <ul>${report.conclusion.map((line) => `<li>${esc(line)}</li>`).join("")}</ul>
</body>
</html>
  `.trim();
}
