import { ReportDocument } from "./types.js";

export function exportReportAsMarkdown(report: ReportDocument): string {
  const out: string[] = [];

  out.push(`# ${report.metadata.title}`);
  out.push("");
  out.push(`- Report ID: ${report.metadata.reportId}`);
  out.push(`- Product: ${report.metadata.product}`);
  out.push(`- Generated by: ${report.metadata.generatedBy}`);
  out.push(`- Created at: ${report.metadata.createdAt}`);
  if (report.metadata.classification) out.push(`- Classification: ${report.metadata.classification}`);
  if (report.metadata.subject) out.push(`- Subject: ${report.metadata.subject}`);
  out.push("");

  out.push("## Executive Summary");
  for (const line of report.executiveSummary) {
    out.push(`- ${line}`);
  }
  out.push("");

  out.push("## Claim Records");
  report.records.forEach((record, idx) => {
    out.push(`### ${idx + 1}. ${record.claim.claimText}`);
    out.push(`- Truth state: ${record.assessment.truthState}`);
    out.push(`- Posterior truth score: ${record.assessment.posteriorTruthScore.toFixed(3)}`);
    out.push(`- Confidence band: ${record.assessment.confidenceBand.toFixed(3)}`);
    out.push(`- Release state: ${record.assessment.releaseState}`);
    out.push(`- Evidence count: ${record.evidence.length}`);
    if (record.fusedSummary) {
      out.push(`- Multimodal structural support: ${record.fusedSummary.structuralSupportScore.toFixed(3)}`);
      out.push(`- Multimodal modalities: ${record.fusedSummary.modalityCoverage.join(", ")}`);
    }
    if (record.reviewTasks && record.reviewTasks.length > 0) {
      out.push(`- Review tasks: ${record.reviewTasks.length}`);
    }
    out.push("");
    out.push("#### Evidence");
    for (const bundle of record.evidence.slice(0, 5)) {
      out.push(`- ${bundle.source.title}: "${bundle.span.quotedText}"`);
    }
    out.push("");
  });

  out.push("## Conclusion");
  for (const line of report.conclusion) {
    out.push(`- ${line}`);
  }
  out.push("");

  return out.join("\n");
}
